-- Table `AUTHZ_PATHS_MAPPING` for classes [org.apache.sentry.provider.db.service.model.MAuthzPathsMapping]
CREATE TABLE `AUTHZ_PATHS_MAPPING`
(
    `AUTHZ_OBJ_ID` BIGINT NOT NULL AUTO_INCREMENT,
    `AUTHZ_OBJ_NAME` VARCHAR(384) BINARY NULL,
    `CREATE_TIME_MS` BIGINT NOT NULL,
    CONSTRAINT `AUTHZ_PATHS_MAPPING_PK` PRIMARY KEY (`AUTHZ_OBJ_ID`)
) ENGINE=INNODB;

-- Table `MAUTHZPATHSMAPPING_PATHS` for join relationship
CREATE TABLE `MAUTHZPATHSMAPPING_PATHS`
(
    `AUTHZ_OBJ_ID_OID` BIGINT NOT NULL,
    `PATHS` VARCHAR(4000) BINARY NOT NULL,
    CONSTRAINT `MAUTHZPATHSMAPPING_PATHS_PK` PRIMARY KEY (`AUTHZ_OBJ_ID_OID`,`PATHS`)
) ENGINE=INNODB;

-- Constraints for table `AUTHZ_PATHS_MAPPING` for class(es) [org.apache.sentry.provider.db.service.model.MAuthzPathsMapping]
CREATE UNIQUE INDEX `AUTHZOBJNAME` ON `AUTHZ_PATHS_MAPPING` (`AUTHZ_OBJ_NAME`);

-- Constraints for table `MAUTHZPATHSMAPPING_PATHS`
CREATE INDEX `MAUTHZPATHSMAPPING_PATHS_N49` ON `MAUTHZPATHSMAPPING_PATHS` (`AUTHZ_OBJ_ID_OID`);

ALTER TABLE `MAUTHZPATHSMAPPING_PATHS` ADD CONSTRAINT `MAUTHZPATHSMAPPING_PATHS_FK1` FOREIGN KEY (`AUTHZ_OBJ_ID_OID`) REFERENCES `AUTHZ_PATHS_MAPPING` (`AUTHZ_OBJ_ID`) ;

------------------------------------------------------------------
-- Sequences and SequenceTables